### ISSUE TITLE
Bug: Link to website on Readme

### ISSUE THREAD

**Issue by connorjoleary** [stevesdawg/govstat#26]
When clicking the link in Chrome, I get `Your connection is not private`. Is the website even still up?

**Comment by acxz** [comment]
Can you specify what link is not working for you?

edit: like actually write down the URL in your issue

**Comment by sseshan7** [comment]
The website is still up, just need to renew my web certificate. Will report back when I do that.

**Comment by connorjoleary** [comment]
> Can you specify what link is not working for you?
> 
> edit: like actually write down the URL in your issue

Sorry, my mistake. The link is: https://govstat.us/

**Comment by sseshan7** [comment]
Renewed the site's web certificate! Should not cause warnings when you visit now.
