### ISSUE TITLE
License

### ISSUE THREAD

**Issue by connorjoleary** [stevesdawg/govstat#27]
I may be interested in expanding upon this repo for future projects, but the default license in Github means `no one may reproduce, distribute, or create derivative works from your work`, so I cannot. Could you please add a license to this project? Info about them can be found [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license).

My preference is the GPU GPL, but it's your call: https://choosealicense.com/licenses/gpl-3.0/

**Comment by acxz** [comment]
@stevesdawg lets get a license up in here

maybe AGPL is better than GPL for this kinda of project
